baseURL = 'https://whoishmp.netlify.app/'
languageCode = 'en-us'
title = 'WhoIsHMP'

[[menu.main]]
identifier = "about-me"
name = "About Me"
url = "/about-me/"
weight = 10

[[menu.main]]
identifier = 'posts'
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 40

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[markup.goldmark.renderer]
  unsafe = true

[params]
math = true
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true

[params.profileMode]
enabled = true
title = "WhoIsHMP"
subtitle = "HMP or Vu Huy Minh Pham. Welcome to my site."
imageUrl = "/ox-hugo/avatar.jpg"
imageTitle = "Linked-In Profile Image"
imageWidth = 120
imageHeight = 120


[[params.profileMode.buttons]]
name = "Who am I?"
url = "/about-me"

[[params.profileMode.buttons]]
name = "Posts"
url = "/posts"

[[params.socialIcons]]
name = "GitHub"
url = "http://github.com/minh-p"

[[params.socialIcons]]
name = "GitLab"
url = "http://gitlab.com/minh-p"

[[params.socialIcons]]
name = "email"
url = "mailto:minhisverynormal@gmail.com"

[[params.socialIcons]]
name = "LinkedIn"
url = "http://www.linkedin.com/in/vu-huy-minh-pham-3115222a0/"
